Add subdivision methods
haesleinhuepf/napari-process-points-and-surfaces pull request #25
Opened 2022-11-17 16:19 UTC by jo-mueller

Hi @haesleinhuepf ,

When I ran the demo notebook with the new vedo methods, I somehow always got an empty surface layer as a result when using the `vedo_subdivide_loop()` function. I added the available methods to the arguments so that they show as a dropdown in napari and can still be used as the basic vedo function (`int` argument indicating the used method).

I thus changed the name of the function to `vedo_subdivide`. 

Let me know what you think!

2022-11-24 18:10 UTC, haesleinhuepf requested changes
Hey Johannes,

thanks for this! It looks amazing. I would like to avoid the Enum for now; until we found a way to make the assistant enum-compatible. Would you mind updating the code as suggested?

Let me know if this makes sense!

Best,
Robert

2022-11-24 18:10 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_vedo.py
> +class subdivision_methods(Enum):
Enums unfortunately don't work well with the assistant. That's why I'm generally trying to avoid them.

2022-11-24 18:10 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_vedo.py
> +def vedo_subdivide(surface:"napari.types.SurfaceData",
Instead of renaming the function, would you mind adding a function `vedo_subdivide_adaptive`? The user could then later in the assistant choose from `vedo subdivide loop` or `vedo subdivide adaptive`.

2022-11-27 08:22 UTC, haesleinhuepf requested changes
Hi Johannes @jo-mueller ,

just a couple of minor things and one question. I would afterwards like to take another quick look and merge.

Thanks!

Best,
Robert

2022-11-27 08:22 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_vedo.py
> +    See Also
```suggestion
    number_of_iterations:int
    
    See Also
```

2022-11-27 08:22 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_vedo.py
> +    loop suubdivision algorithm.
```suggestion
    loop subdivision algorithm.
```

2022-11-27 08:22 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_vedo.py
> +    The position of the created triangles is determined by  a
```suggestion
    The position of the created triangles is determined by a
```

2022-11-27 08:22 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_vedo.py
> +    See Also
```suggestion
    number_of_iterations:int
    
    See Also
```

2022-11-27 08:22 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_vedo.py
> +    See Also
```suggestion
    number_of_iterations:int
    
    See Also
```

2022-11-27 08:22 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_vedo.py
> +    See Also
```suggestion
    number_of_iterations:int
    
    See Also
```

2022-11-27 08:22 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_vedo.py
> +                   ) -> "napari.types.SurfaceData":
Can this function be removed? We have all four subdivision above, right?

2022-11-27 08:22 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_vedo.py
> +class subdivision_methods(Enum):
Can we remove the Enum now?

2022-11-28 08:20 UTC, jo-mueller commented on napari_process_points_and_surfaces/_vedo.py
> +                   ) -> "napari.types.SurfaceData":
Yes, they are all in their separate function now. I removed the old one in 6b1c56abd5eb50d36cbf8cd2b261a9de0042638c

2022-11-28 08:23 UTC, jo-mueller commented
Hi @haesleinhuepf ,

thanks for taking a look at it. I removed the remainders of the previous implementation in 6b1c56abd5eb50d36cbf8cd2b261a9de0042638c. The other commit (178ba56abf48c3544d63d83ea6d1965d53edcf2d) just features some auto-format that's done automatically by VSCode for Python. Hope you don't mind 😬

2022-12-11 09:40 UTC, merged