Add curvature measurements
haesleinhuepf/napari-process-points-and-surfaces pull request #5
Opened 2022-03-07 16:26 UTC by jo-mueller

2022-03-07 20:16 UTC, haesleinhuepf requested changes
Hi Johannes,

super cool, thanks for your contribution here! I'd like to ask for some changes. In the other functions I tried to mimic the vedo and open3d API. Hence, I'd suggest to name a function "add_curvature_scalars" if a function with this name exists in vedo and we're just doing the same here. Also some docstrings with explanations of what functions do would be great.

Otherwise great! I will merge soon after you did these little modifications.

Thanks again :-)

2022-03-07 20:16 UTC, haesleinhuepf commented on tox.ini
> +	open3d
```suggestion
```
I think those are not necessary as they are specified in setup.cfg

2022-03-07 20:16 UTC, haesleinhuepf commented on setup.cfg
> +version = 0.1.3
```suggestion
version = 0.1.2
```
I'd like to bump the version when a new release is deployed

2022-03-07 20:16 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_quantification.py
> +def add_curvature(surface: SurfaceData, curvature_id: Curvature = Curvature.Gauss_Curvature) -> SurfaceData:
How about naming the function "add_curvature_scalars"?

And could you please add a link to the vedo documentation and a docstring?

https://vedo.embl.es/autodocs/content/vedo/mesh.html#vedo.mesh.Mesh.addCurvatureScalars

2022-03-07 20:16 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_quantification.py
> +def spherefitted_curvature(surface: SurfaceData, radius: float = 1.0) -> List[LayerDataTuple]:
How about naming the function "measure_sphere_fitted_curvature"?

2022-03-07 20:16 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/__init__.py
> +__version__ = "0.1.3"
```suggestion
__version__ = "0.1.2"
```
Leave version bumps to the maintainer ;-)

2022-03-07 20:16 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_quantification.py
> +    Minimum_Curvature = 3
According to the vedo documentation, those are called:
0-gaussian, 1-mean, 2-max, 3-min curvature

Can we please have the same names here? This makes it later easier to use.

2022-03-07 20:19 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_quantification.py
> +    props_res = {'name': 'fit residues', 'colormap': 'magma'}
One more thing: If a variable contains "probability fit residues", please call the variable "probability_fit_residues". "pro_res" is no meaningful name. Also consider renaming "props_curv". Please use english words for variable names. Thank you!

2022-03-07 23:35 UTC, jo-mueller commented on napari_process_points_and_surfaces/_quantification.py
> +    Minimum_Curvature = 3
Yes and no - they're only half called that way. They are referred as such inn the documentation but if you wanted to retrieve the actual data from the pointcloud object you would have to use `mesh.pointdata['Gauss_Curvature ']` or `mesh.pointdata['Maximum_Curvature ']`. I find the API not 100% consistent on this one.

2022-03-08 05:56 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_quantification.py
> +    Minimum_Curvature = 3
👍

2022-03-08 08:37 UTC, jo-mueller commented on tox.ini
> +	open3d
Really? I didn't know, cool :)

2022-03-08 12:31 UTC, jo-mueller commented
Hey @haesleinhuepf 

thanks for the fast feedback! Next time feel free to wait a little longer until I change the PR to be ready for review :)

2022-03-08 13:04 UTC, jo-mueller commented
PS: I ran tests with tox which run for Python 3.8 and 3.9 but fail for 3.7, which seems to be a pytest issue rather than an issue with the tests/the functions

2022-03-12 11:10 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/__init__.py
> +@register_action(menu = "Surfaces > Example data: Ellipsoid (vedo)")
```suggestion
@register_action(menu = "Surfaces > Example data: Ellipsoid (vedo,)")
```

2022-03-12 11:14 UTC, haesleinhuepf approved these changes
Hi Johannes @jo-mueller ,

this all looks good to me, just some minor things.

Thanks!
Robert

2022-03-12 11:14 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_quantification.py
> +        3-tuple consiting of (points, faces, values)
```suggestion
        3-tuple consisting of (points, faces, values)
```

2022-03-12 11:14 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_quantification.py
> +        residue-annotated surface.
Can you maybe add a sentence above that explains what a "fit residue-annotated surface" is?

2022-03-12 11:14 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_quantification.py
> +    return [layer1, layer2]
```suggestion
    return [layer1, layer2]

```

2022-03-14 08:22 UTC, jo-mueller commented on napari_process_points_and_surfaces/_quantification.py
> +        residue-annotated surface.
```
    List[LayerDataTuple]
        A list of surface data items. The items correspond to the curvature- and
        fit residue-annotated surface, respectively. 
        With each item consisting of a `(points, faces, values)` tuple, the 
        `value` variable reflects each vertice's curvature or fit residue result.'
```

2022-03-20 15:19 UTC, haesleinhuepf commented
Great work Johannes @jo-mueller! Thanks a lot!

2022-03-20 15:19 UTC, merged