Apply scale
haesleinhuepf/napari-process-points-and-surfaces pull request #8
Opened 2022-03-22 09:18 UTC by jo-mueller

Fixes #6

2022-03-22 18:42 UTC, haesleinhuepf requested changes
Hey Johannes @jo-mueller ,

thanks for working on this.

I'm wondering if it is possible to write a bit cleaner code. I suggest, either all functions consume layers or all functions consume nparrays. That would make it easier to maintain later.

I often see syntax like `labels_data: Union[[napari.layers.Labels, napari.types.LabelsData]]` as parameter type annotation. Have you tested this from napari? If you run this function from within napari, how does the user-interface look like? I'm wondering how magicgui can guess how to build a user-interface for this type...

Thanks!
Robert

2022-03-22 18:42 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/__init__.py
> +    labels_stack = np.zeros(as_large_as_image.data.shape, dtype=int)
Will this work if `as_large_as_image` is of type `LayerData`?

2022-03-22 18:42 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/_tests/test_function.py
> +    test_something(napari.Viewer)
```suggestion
```

You do not need this if you run `pytest -k test_curvature` from the command line.

2022-03-22 18:42 UTC, haesleinhuepf commented on napari_process_points_and_surfaces/__init__.py
> +    if isinstance(labels, Labels):
I'm suspecting this will never be true because of lines 441/442 above

2022-03-23 08:25 UTC, jo-mueller commented
Hey @haesleinhuepf 

> I'm wondering if it is possible to write a bit cleaner code?

Sorry about that. I changed the PR to draft mode for fixing it up and will notify you once it's ready for review.

>I suggest, either all functions consume layers or all functions consume nparrays. That would make it easier to maintain later.

In that case it would have to be layers - otherwise there's no way to access the scale parameter inside a function.

2022-03-28 08:37 UTC, closed without merging